### PR TITLE
enable Gradle wrapper validation

### PR DESCRIPTION
**Pull request by sullis**
## Description

enable Gradle wrapper validation

https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action

## Breakdown

n/a

## Validation

GitHub Actions runs the workflow.

## Additional Notes

n/a

## Submission Checklist
 - [ ] The source has been evaluated for semantic versioning changes and are reflected in ```versionName``` under `app/build.gradle`
 - [ ] The `CHANGELOG.md` reflects any **feature**, **bug fixes**, or **known issues** made in the source code

### CODE REVIEW

**Comment by sullis** [comment]
GitHub Actions Workflow executed on my fork:
https://github.com/sullis/twilio-video-app-android/actions/runs/585020495

Result:

Screen Shot 2021-02-20 at 1 21 20 PM

```
Found unknown Gradle Wrapper JAR files:

  e2b82129ab64751fd40437007bd2f7f2afb3c6e41a9198e628650b22d5824a14 gradle/wrapper/gradle-wrapper.jar
```

**Comment by sullis** [comment]
@Alton09  Gradle's Wrapper Validation does not recognize the JAR file in this repo

```
gradle/wrapper/gradle-wrapper.jar 
```

**Comment by Alton09** [comment]
Thank you for the pull request and contributing to this project @sullis! I'll take a closer look at this one soon to see if we can merge it in. From a quick glance though, it definitely appears to be a betterment.

**Comment by Alton09** [comment]
Our team has decided to close this pull request as our current CI/CD pipeline is managed through Circle CI and adding a GitHub Action would complicate the development workflow. Thanks for the pull request though @sullis !

**Pull request closed without merging**
